### ISSUE TITLE
< and > symbols do not render correctly

### ISSUE THREAD

**Issue by fahran** [itsmichaelwang/mobile-wizard#1]
The character encoding for < and > is a little off - you're rendering the HTML character entities &lt; and &gt; instead. 

Visible here: http://www.reddit.com/r/worldnews/comments/2j4zkd/giant_squid_attacks_greenpeace_submarine/cl8j7yr

http://i.imgur.com/77hZBVP.png

Nice little bot - thanks for making it :D

**Comment by itsmichaelwang** [comment]
Fahran,

I modified the bot so it uses Python's HTMLParser to convert HTML entities to utf-8 text. As you can see, it has no problems handling < and > signs: http://www.reddit.com/r/mobilewizard/comments/2j6415/html_part_iii/cl8pr32?context=10000
